apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zeus.fullname" . }}-config
  labels:
    {{- include "zeus.labels" . | nindent 4 }}
data:
  {{- with .Values.configMap.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}